# Introduction to Python

This notebook aims at giving you a first glimpse at python's syntax and its possibilities. This versatile language is widely used, not only for Machine Learning and Data Science in general, but for many other applications, both in the industry and academia, and will be very useful for your career.

A more in depth introduction to base Python is already given in parallel in the ongoing course "Technologies and Architectures for Data" by Prof. Dimitri Konstantas and Cinzia Tarantino. In this notebook, we will quickly recall the important python data types that you will certainly come across, as well as the syntax for the basic programing principles (loops, conditions, functions, classes). The other notebook available on moodle (`Introduction_to_python_modules.ipynb`) will go a bit more in depth with the essential python modules (libraries), that you will need for this course (and for almost any Data Science project).

Depending on your personal programming background and skills, learning a new programming language can be a lot of new information at once. Feel free to go through these notebooks at your pace and multiple times to really understand the concepts shown here through examples that you can run, modify, and play a bit with.

If you need further explanations about programming in Python, we can, for example recommend:
- https://openclassrooms.com/en/courses/2304731-learn-python-basics-for-data-analysis for Python beginners,
- https://jakevdp.github.io/PythonDataScienceHandbook/ a very good book teaching Numpy, Pandas, Matplotlib,
- https://www.youtube.com/playlist?list=PL-osiE80TeTsqhIuOqKhwlXsIBIdSeYtc an introduction to object oriented programming (OOP). Note that this goes beyond the level expected for the course.

Search engines are also a very useful tool when you will be stuck. The python community is *very* active, you will, in most cases, find a rapid answer to your "*how to ...*" questions!
Discussing with other students is also highly encouraged, to help each other out and learn in groups (as long as you don't share your final answers for graded materal). And of course, don't hesitate to ask your questions to the TAs when you are stuck.

## A word on IPython Jupyter notebooks

In the Anaconda environment, python code can be run in different manners. One could use simple `*.py` scripts, that can be edited, for example with the Spyder software (Also provided in Anaconda), similarly to `*.R` sripts edited with RStudio.

Another way is to use `*.ipynb` notebooks (as the one you are looking at), which come in handy for Data analysis tasks for example, as you can structure and present your projects nicely with comments and written analysis between code cells.

In notebooks, both code and markdowns can be run and rendered successively with `Shift` + `Enter`. You can switch a cell from code to markdown by pressing `Esc` and then `M`, or with the menu above. Double click on a rendered markdown (this one, or the title above for example) to edit it.

Markdowns are a WYSIWYG (What You See Is What You Get) environment. It is possible for example to use **bold**, *italic*, and `verbatim`.

    This is also some verbatim code.
    $ echo "hi"

- This is a list,
- with two entries...

1. and this a enumerated one,
1. with two entries as well.

LaTeX code is also possible: $E=mc^2$,
$$
\int_{-\infty}^\infty f(t) e^{-i\omega t} dt.
$$

Feel free to spend some time getting familiar with the environment and to play a bit with the menu above to learn how to create, move, delete cells, and anything else that you would need.

## Basic data types

### Numbers, text and booleans

The syntax for the most basic types and for variable attribution is similar to a lot of other (interpreted, non-typed) programming languages you may be familiar with. Here are some examples:

In [1]:
some_integer = 2
some_integer #(the last called object in the cell is shown in "Out")

2

In [2]:
# Other examples printed with the "print" function
print("integers:", 4)
print("floats:", 12.46, 1.3e4)
print("strings:", "Hello World!")
print("Complex numbers:", 4 + 3j)

integers: 4
floats: 12.46 13000.0
strings: Hello World!
Complex numbers: (4+3j)


In [3]:
print("Booleans:", True, False)
print("Booleans (2):", (1>2 or 4>=3) )

Booleans: True False
Booleans (2): True


In [4]:
a=2
print("Type of 'a' is:")
type(a)

Type of 'a' is:


int

In [5]:
example_string = "Hello"
print("First Letter of", example_string, "is", example_string[0])#Note that indexing starts at 0 in python
print("Last Letter of", example_string, "is", example_string[-1])# [-1] Accesses the last element of an ennumerable object

First Letter of Hello is H
Last Letter of Hello is o


In [6]:
combined_string = example_string + " everyone"
combined_string

'Hello everyone'

### Data Containers

For sequences, the most used base types are lists:

In [7]:
my_list = [2, 6, 4, 432, 36]
my_list

[2, 6, 4, 432, 36]

In [8]:
my_list[1:4]  #carefull: 1:4 returns the values indexed at 1, 2 and 3 but NOT at 4

[6, 4, 432]

In [9]:
my_list + [12]

[2, 6, 4, 432, 36, 12]

In [10]:
[2, 4, "sd", True, ["inner","list"]] # lists can contain different subtypes, even other lists

[2, 4, 'sd', True, ['inner', 'list']]

and "tuples" (often returned by functions ,as shown a bit below in the next sections) which are the "immutable" version of lists:

In [11]:
my_tuple = (2,56,3)
my_tuple

(2, 56, 3)

In [12]:
my_1D_tuple = (4,)
my_1D_tuple

(4,)

There are also sets (any value can appear only once):

In [13]:
my_set = {12, "w", 12}
my_set

{12, 'w'}

and dictionaries, that can be seen as named lists:

In [14]:
my_dict = {"name": "Sophie",
           "Age": 23,
           "Passions": ["Tennis", "Machine Learning"]}
my_dict

{'name': 'Sophie', 'Age': 23, 'Passions': ['Tennis', 'Machine Learning']}

In [15]:
my_dict["Age"]

23

## Programming principles

In python, loops, conditions et function definitions use colons (:) and tabulation instead of brackets, which are used in some other languages (like R).

### Loops

Here are some useful examples of some for loops:

In [16]:
for i in range(0,4):
    temp = i*2
    print(i, "* 2 =", temp)

0 * 2 = 0
1 * 2 = 2
2 * 2 = 4
3 * 2 = 6


In [17]:
# Note that the scope of variable transcends loops in python,
# e.g., we can access the enumeration index and variables defined inside of the loop, outside of it:
print(i, temp)

3 6


In [20]:
list_to_enumerate_on = ["a", "b", "c"]

for i, el in enumerate(list_to_enumerate_on):
    print(i, "-", el)

0 - a
1 - b
2 - c


In [21]:
# a dumy while loop (for syntax would be preferable here)
i=0
while(i<3):
    print(i)
    i = i+1

0
1
2


In some cases, simple for loops can be written in a single line list syntax in python, which can come in pretty handy sometimes. Here is an example:

In [22]:
my_list2 = [2, 6, 4]
one_line_loop_result = [i * 2 for i in my_list2]
one_line_loop_result

[4, 12, 8]

### Conditions

If - else conditions are pretty straight forward:

In [23]:
cond = 4 > 35

if (cond):
    print("4 is greater than 35")
else:
    print("4 is NOT greater than 35")
        

4 is NOT greater than 35


In [24]:
if (4 > 35):
    print("4 is greater than 35")
    
elif (4 == 35):
    print("4 equals 35")
        
else:
    print("35 is greater than 4")

35 is greater than 4


Conditions can also be added to one line for loops. Here are two examples for the same one-line loop as above:

In [25]:
my_list2 = [2, 6, 4]
one_line_loop_result = [i * 2 for i in my_list2 if i <= 5]
one_line_loop_result

[4, 8]

In [26]:
my_list2 = [2, 6, 4]
one_line_loop_result = [i * 2 if (i <= 5) else "exception" for i in my_list2]
one_line_loop_result

[4, 'exception', 8]

### User defined functions

Functions are very usefull for modularity and code clarity. Especially if there a task is repeated more than once, a function is always better than repeating code!

One can define a python function and use it, for example, in the following way:

In [27]:
def my_function(a, b, c):
    """
    Short description of the function 1.
    """
    result = (a + b) / c
    return(result)

In [28]:
fct_result = my_function(3, 7, 2)
fct_result

5.0

Multiple outputs are possible (returning tuples):

In [29]:
def my_multi_function(a, b, c):
    """
    Short description of the function 2.
    """
    result1 = (a + b) / c
    result2 = (a - b) / c
    
    return(result1, result2)

In [30]:
fct_result2 = my_multi_function(3, 7, 2)
fct_result2

(5.0, -2.0)

The outputs can directly be stored in separate variables:

In [31]:
res1, res2 = my_multi_function(3, 7, 2)
print(res1)
print(res2)

5.0
-2.0


Separating your code in different meaningful functions is in general very recommended, as it makes your code clearer, cleaner, and helps avoiding copy-pasting (which is a very bad coding practice, as it is very error-prone once something that has been copy-pasted needs modifications).

As for lists, functions can be defined in a one-line manner in python, with `lambda`:

In [32]:
one_line_fct = lambda x, y: (x+y)**2
one_line_fct(2,3)

25

## Python modules (libraries)

You can import python libraries with the `import` command, for example, the numpy module can be imported as follows:

In [33]:
import numpy

Then, the module's variables, functions, classes, ... can be accessed with the dot (.):

In [34]:
numpy.array([1,2]) # This creates a numpy array (more details in the other notebook on modules)

array([1, 2])

Module imports can be given aliases, for example, numpy is more often imported as:

In [35]:
import numpy as np

Then, for example, the same line as above becomes:

In [36]:
np.array([1,2,3])

array([1, 2, 3])

another example, with the "random" sub-module of numpy:

In [37]:
np.random.randn(2) #gaussian sample of size 2, from numpy's 'random' submodule

array([0.20706094, 1.3696847 ])

One can import only specific function or submodules in the main namespace. For the same examples:

In [38]:
from numpy import array, random

In [39]:
array([1, 2])

array([1, 2])

In [40]:
random.randn(2)

array([-1.88849777,  0.1974891 ])

It is also possible to import everything from a module into the main namespace, although it is really not recommended, especially for big modules as numpy, as functions can overlap with existing ones. It is thus better to use each module in their own namespace separately as above (e.g. with `import numpy as np`).

In [ ]:
# !! NOT RECOMMENDED !!

#from numpy import *

Although this can be useful to import functions from a custom created file. Suppose we have a script containing some functions in the same folder as this notebook, named `my_functions.py` then you can import these functions with:

    from my_functions import *

The notebook `Introduction_to_python_modules.ipynb` available on moodle introduces some important python modules that are widely used for many (if not all) data-related applications: `numpy`, `pandas`, `matplotlib` and `scikit-learn`.

## Introduction to object-oriented programming

Python is an object-oriented language. OOP is a very powerful coding paradigm that is widely used in many languages. It helps structuring the code around objects, and makes, arguably, the code much cleaner and clearer to read and conceptualize. It also makes it easier to model concrete real-world concepts into code. Many python modules are centered around this principle.

Formally, in OOP, we can define what we call **classes**. A class is like a blueprint that describes an object. Such an object can have (among other things):
- properties (that we call **attributes**) which are inner variables of the objects, containing data, and
- behaviours (that we call **methods**) that are inner functions of the objects.

For example, let's say that we want to define a class that represents dogs. Then its attibutes could be: its name, its age, its weight, its color, etc... and its methods could be: to bark, to run, to bathe, etc...

Once we defined a class (i.e. the blueprint with its corresponding attributes and methods), we can create actual objects (that we call **instances**) from this "blueprint".

You are not required to know how to define classes for this course, but we believe that some OOP notions will help you better understand what you are actually doing when you use this course's required modules, like `scickit-learn` and `pandas`, that are designed around this paradigm.

For example, we could create the class dog as follows:

In [41]:
# ( This cell is a bit more advanced, you might skip the details as long as you understand the main idea )
class Dog:
    def __init__(self, name, age):
        #This method is called to initialize the instance when created from the class
        #Here we can define the atributes of the class
        self.name = name
        self.age = age
        self.dirty = False
    
    # Below are the other methods of the class
    
    def bark(self):
        print(self.name, "says 'Waf, Waf!'")
    
    def run(self, nb_meters):
        # If the Dog runs more than 100 meters, it gets dirty.
        if(nb_meters >= 100):
            print("I am dirty.")
            self.dirty = True
    
    def bathe(self):
        print("I am clean.")
        self.dirty = False
    
    def get_stick(self):
        # The Dog returns a wild stick
        return("stick")

We can then instantiate a dog from the class (i.e. create a dog from the blueprint):

In [42]:
dog1 = Dog(name = "Johnny", age = 8)

Wow, `dog1` is now a `Dog` called Johnny of age 8 which is clean (by default). We can then use its attributes and methods (that might modify some aspects of Johnny). Here are a few examples:

In [43]:
dog1.name

'Johnny'

In [44]:
dog1.dirty

False

In [45]:
dog1.bark()

Johnny says 'Waf, Waf!'


In [46]:
dog1.run(nb_meters=3)

In [47]:
dog1.dirty

False

In [48]:
dog1.run(nb_meters=112)

I am dirty.


In [49]:
dog1.dirty

True

In [50]:
dog1.bathe()

I am clean.


In [51]:
dog1.dirty

False

In [52]:
surprise = dog1.get_stick() #Johnny got you a surprise
surprise

'stick'

In [53]:
dog1.name = "Jean-Claude" #dog1 changes its name

#(defining a method change_name() would be cleaner than modifying the attribute directly like that)

In [54]:
dog1.name

'Jean-Claude'

The example above is maybe simpler in comparison, but you are conceptually doing the same things when you deal with `pandas` or `sklearn`, as `DataFrame` and any machine learning models are defined as classes, that you use instances of, and call methods from, with the same syntax as above.

You can now read again the notebook `Introduction_to_python_modules.ipynb`, where you should be able to understand more easily what the syntax actually means in terms of attributes, methods classes and instances, especially for the `pandas` and `sklearn` parts.

Note that, in `numpy` and `pandas` for example, some methods aiming at changing the data or data structure of a class instance (an array or  DataFrame, respectively) are not "*in place*". This means that the methods return the modified object (e.g. `reshaped_array = some_np_array.reshape(2,3)`) instead of modifying the instance itself (as in `dog1.bathe()` above). This behaviour can be controlled in some `pandas` methods with the `inplace = True/False` argument (e.g `df.drop("row_name", inplace=True)` actually removes a row from `df`, whereas `df2 = df.drop("row_name")` returns `df` without the specified row into `df2`).